### ISSUE TITLE
Setup Monorepo and Next.js App

### ISSUE THREAD

**Issue by MuhammadFariMadyan** [lampungdevtech/lampungdev-platform#4]
# 🧩 Task: Setup Monorepo and Next.js App

**Description:**  
Initialize the **LampungDevTech** website project using **NX Workspace** as a monorepo structure, with a **Next.js** frontend application styled using **Tailwind CSS**.

---

## ✅ Checklist

- [x] **Initialize NX Workspace & Generate Next.js App**
  - Run: `npx create-nx-workspace@latest lampungdevtech-platform`
  - Here's the samples answer:
✔ Which stack do you want to use? ·`react`
✔ What framework would you like to use? · `nextjs`
✔ Application name · `web`
✔ Would you like to use the App Router (recommended)? · `Yes`
✔ Would you like to use the src/ directory? · `No`
✔ Which unit test runner would you like to use? · `jest`
✔ Test runner to use for end to end (E2E) tests · `cypress`
✔ Default stylesheet format · `tailwind`
✔ Would you like to use ESLint? · `Yes`
✔ Would you like to use Prettier for code formatting? · `Yes`
✔ Which CI provider would you like to use? · `github`
  - Verify that `apps/web` is created
  - Install libraries `npm install` in `apps/web`
  - Test with `nx dev web`

- [x] **Integrate Tailwind CSS**
  - Confirm Tailwind setup; if not:
    ```bash
    npm install -D tailwindcss postcss autoprefixer
    npx tailwindcss init -p
    ```
  - Configure `tailwind.config.js`
  - Add Tailwind directives to `styles.css`:
    ```css
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
    ```

- [x] **Setup Project Folder Structure Next.js**
  - Create folders under `apps/web`:
    - `components`
    - `app/`
    - `assets`

- [x] **Setup GitHub Actions for CI**
  - Add basic workflow in `.github/workflows/ci.yml`:
    ```yml
    name: CI

      on:
        push:
          branches: [main]
        pull_request:
          branches:
            - main
            - 'feature/**'
      
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: npm install --legacy-peer-deps
            - run: npx nx build web
    ```
